support Ubuntu 'redis-server' package. version : 2.2.12-1build1 .

diff --git a/templates/default/redis_init.erb b/templates/default/redis_init.erb
--- a/templates/default/redis_init.erb
+++ b/templates/default/redis_init.erb
@@ -23,15 +23,16 @@
 REDISPORT=<%= @port %>
 
 <% if node.redis.install_type == "source" %>
-EXEC=<%= node.redis.dst_dir %>/bin/redis-server
+DAEMON=<%= node.redis.dst_dir %>/bin/redis-server
 CLIEXEC=<%= node.redis.dst_dir %>/bin/redis-cli
 <% else %>
-EXEC=<%= node.redis.dst_dir %>/redis-server
+DAEMON=<%= node.redis.dst_dir %>/redis-server
 CLIEXEC=<%= node.redis.dst_dir %>/redis-cli
 <% end %>
 
 PIDFILE=<%= @pidfile %>
-CONF="<%= @conf_dir %>/<%= @name %>.conf"
+DAEMON_ARGS="<%= @conf_dir %>/redis.conf"
+RUNDIR=/var/run/redis
 
 <% if node.platform_family == "debian" %>
 ulimit -Hn <%= node.redis.ulimit %>
@@ -39,32 +40,42 @@ ulimit -Sn <%= node.redis.ulimit %>
 <% end %>
 
 case "$1" in
-    start)
-        if [ -f $PIDFILE ]
+  start)
+        echo -n "Starting $DESC: "
+        mkdir -p $RUNDIR
+        touch $PIDFILE
+        chown redis:redis $RUNDIR $PIDFILE
+        chmod 755 $RUNDIR
+        if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
         then
-                echo "$PIDFILE exists, process is already running or crashed"
+                echo "$NAME."
         else
-                <% if @logfile.downcase != "stdout" %>
-                chown -R <%= @user %>:<%= @user %> <%= @logfile %>
-                <% end %>
-                echo "Starting Redis server..."
-                sudo -u <%= @user %> $EXEC $CONF
+                echo "failed"
         fi
         ;;
-    stop)
-        if [ ! -f $PIDFILE ]
+  stop)
+        echo -n "Stopping $DESC: "
+        if start-stop-daemon --stop --retry forever/QUIT/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
         then
-                echo "$PIDFILE does not exist, process is not running"
+                echo "$NAME."
         else
-                PID=$(cat $PIDFILE)
-                echo "Stopping ..."
-                $CLIEXEC -p $REDISPORT shutdown
-                while [ -x /proc/${PID} ]
-                do
-                    echo "Waiting for Redis to shutdown ..."
-                    sleep 1
-                done
-                echo "Redis stopped"
+                echo "failed"
+        fi
+        rm -f $PIDFILE
+        ;;
+  restart|force-reload)
+        ${0} stop
+        ${0} start
+        ;;
+
+  status)
+        echo -n "$DESC is "
+        if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
+        then
+                echo "running"
+        else
+                echo "not running"
+                exit 1
         fi
         ;;
     *)
